:asciidoc: https://asciidoctor.org[AsciiDoc]
:asciidoctorjs-extensions: https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/ecosystem[Asciidoctor.js Extensions]
:asciidoctorjs: https://docs.asciidoctor.org/asciidoctor.js/latest[Asciidoctor.js]
:bash: https://www.gnu.org/software/bash[Bash]
:confluence-api-token: https://id.atlassian.com/manage/api-tokens[API token]
:confluence: https://www.atlassian.com/software/confluence[Confluence]
:gfm: https://github.github.com/gfm[GitHub Flavored Markdown]
:github-actions: https://docs.github.com/actions[GitHub Actions]
:kroki: https://github.com/Mogztter/asciidoctor-kroki[Asciidoctor Kroki Extension]
:nodejs: https://nodejs.org[Node.js v16+]
:pandoc: https://pandoc.org[Pandoc]
:repo-root: https://github.com/fardjad/node-ascaid/tree/master
:wsl: https://docs.microsoft.com/en-us/windows/wsl[WSL]

== ascaid: a collection of AsciiDoc tools

[svgbob]
....
  ___   _____ _____   ___ ______ _____
 / _ \ /  ___/  __ \ / _ \|  _  \  ___|
/ /_\ \\ `--.| /  \// /_\ \ | | | |__
|  _  | `--. \ |    |  _  | | | |  __|
| | | |/\__/ / \__/\| | | | |/ /| |___
\_| |_/\____/ \____/\_| |_/___/ \____/
....

=== Description

*ascade* is a CLI tool for writing and publishing {asciidoc} files. It uses {asciidoctorjs} and {pandoc} under the hood and has the following main features:

* It can be configured to load {asciidoctorjs-extensions}
* It includes a live server to help with writing AsciiDoc documents
* It can convert Asciidoc files to {gfm}
* It can publish GitHub Flavored Markdown files to {confluence}

The following diagram shows a typical document writing and publishing workflow with *ascaid*.

[mermaid]
....
%%{init: {'theme':'neutral'}}%%
graph LR
  Writer["Document Writer"] -- Writes --> ADOC
  ADOC -- ascaid serve --> LivePreview["Live Preview"]
  ADOC["AsciiDoc Documents"] -- ascaid adoc-to-gfm --> GFM["GitHub Flavored Markdown Documents"] -- Gets rendered in --> RHS["Code Hosting Services (i.e. GitHub, GitLab, etc.)"]

  GFM -- ascaid gfm-to-confluence --> Confluence
....

_Note: This document is generated with_ *_ascaid_*. _Check out the source {repo-root}/adocs/[here]._

=== Requirements
. A Unix-like operating system ({WSL} is also supported)
. {bash}
. {nodejs}
. {pandoc}

=== Installation

You can install the package globally with npm:

----
npm install -g ascaid
----

=== Commands

==== `ascaid help`

exec::[command="node ../cli/ascaid.js help"]

==== `ascaid serve`

exec::[command="node ../cli/ascaid.js help serve"]

==== `ascaid adoc-to-gfm`

exec::[command="node ../cli/ascaid.js help adoc-to-gfm"]

==== `ascaid gfm-to-confluence`

exec::[command="node ../cli/ascaid.js help gfm-to-confluence"]

=== Config File

You can configure *ascaid* to load additional extensions by creating a file named `ascaid.config.json` in the current working directory. An example can be found {repo-root}/examples/asciidoctor-extension[here].

{kroki} is included by default for convenience.

=== GitHub Actions Usage

To publish documents to confluence you'll need to create an {confluence-api-token} and a root page to publish the documents under.

An example {github-actions} YAML file can be found {repo-root}/examples/github-actions-public-to-confluence/public-docs.yml[here].
