---
name: publish-docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: fardjad/ascaid:latest
          options: -v ${{ github.workspace }}/docs:/docs
          run: >
            /opt/node-ascaid/cli/ascaid gfm-to-confluence /docs
            --api-base-url https://<SUBDOMAIN>.atlassian.net/wiki/rest/api
            --api-username <YOUR_USERNAME>
            --api-password ${{ secrets.CONFLUENCE_API_PASSWORD }}
            --space-key <SPACE_KEY>
            --root-page-id <ROOT_PAGE_ID>
            --root-page-title "ascaid"
