name: Test and Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".husky/**"
      - "adocs/**"
      - "docs/**"
      - "examples/**"
      - "media/**"
      - "LICENSE"
      - "publish.sh"
  pull_request:
    paths-ignore:
      - ".husky/**"
      - "adocs/**"
      - "docs/**"
      - "examples/**"
      - "media/**"
      - "LICENSE"
      - "publish.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
      fail-fast: true
    steps:
      - uses: actions/checkout@main
      - uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: "2.17.1.1"
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@main
        env:
          cache-name: cache-node-${{ matrix.node }}-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: npm ci
      - name: Tests
        run: npm test
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@main
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rickstaa/action-create-tag@main
        if: steps.check.outputs.changed == 'true'
        with:
          tag: v${{ steps.check.outputs.version }}
          message: v${{ steps.check.outputs.version }}
      - uses: ncipollo/release-action@main
        if: steps.check.outputs.changed == 'true'
        with:
          name: v${{ steps.check.outputs.version }}
          tag: v${{ steps.check.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@main
        if: steps.check.outputs.changed == 'true'
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@main
        env:
          cache-name: cache-node-${{ matrix.node }}-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
